feather.replace()
require('/public/js/jquery-3.6.1.min');
require('/public/js/modernizr.custom');
require('/public/js/animating');
require('/public/js/imagesloaded.pkgd.min');
require('/public/js/perfect-scrollbar.min');
require('/public/js/jquery.shuffle.min');
require('/public/js/masonry.pkgd.min');
require('/public/js/owl.carousel.min');
require('/public/js/jquery.magnific-popup.min');
require('/public/js/jquery.googlemap');
require('/public/js/validator');
require('/public/js/main');
